apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  annotations:
    harness.io/managed: true
  name: {{.Values.name}}-destinationrule
spec:
  host: {{.Values.name}}-svc
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    harness.io/managed: true
  name: {{.Values.name}}-virtualservice
spec:
  gateways:
  - {{.Values.name}}-gateway
  hosts:
  - test.com
  http:
  - route:
    - destination:
        host: {{.Values.name}}-svc
